### ISSUE TITLE
Using em over px in min-width?

### ISSUE THREAD

**Issue by ghost** [tachyons-css/tachyons-text-align#1]
Question: 

Why are you using `em` over the more common `px` for designating `min-width` (for screen sizes)? 

Just curious. :smiley:

**Comment by mrkhdly** [comment]
Tachyons v5 will become a monorepo so this issue is being closed, if the issue is still relevant please open an issue with the main repo https://github.com/tachyons-css/tachyons/issues/new & link to this one
